= nutpp Installation Guide
Cristian Ciocaltea <cristian.ciocaltea@gmail.com>
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toc:
:sectnums:
:sectanchors:
:sectlinks:
:NUTPP_DIR: /home/guest/nutpp
:BUILD_DIR: /home/guest/build
:DIST_DIR: {BUILD_DIR}/dist

== Intro

This document describes the build and install procedure for the _nutpp_
application and some of its dependencies.

[IMPORTANT]
The primary build platform is based on Ubuntu 16.04, therefore some of the
commands bellow may require some tuning in order to run on other platforms.
To speedup the compilation, commands that support parallel build make use
of the `nproc` tool to receive the number of available CPU cores. On Ubuntu
this is part of the `coreutils` package. If your platform doesn't provide
this utility, you might want to replace `$(proc)` with the actual CPU cores
count.

.Build requirements
* GCC v5+ or an alternative compiler with basic $$C++14$$ support:
  Visual Studio 2015, Clang v3.3+)
* GNU Make or The Microsoft Program Maintenance Utility (NMAKE.EXE)
* CMake v3.5+
* Log4cplus v1.21
* Wt v4.0.2
 - Boost
 - OpenSSL
 - Sqlite
* Doxygen (optional)

.Build environment
* Root location for building packages: `{BUILD_DIR}`
* Root location for installing packages: `{DIST_DIR}`


== Install build dependencies

=== CMake

Minimum required version is 3.5.

==== On Linux

[source,sh]
$ sudo apt-get install cmake
$ cmake -version

[WARNING]
--
Usually the standard distributions offer older versions of CMake (e.g.
in Ubuntu 14.04 the CMake version is 2.8).

If you have installed an older version of CMake you need to remove it
first and then install it from a 3rd party repository:
[source,sh]
$ sudo apt-get purge cmake
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:george-edison55/cmake-3.x
$ sudo apt-get update
$ sudo apt-get install cmake
--

==== On Windows

Download and install https://cmake.org/download/[cmake for Windows].

[TIP]
Make sure the CMake binary folder has been properly configured in the PATH
environment. E.g.: `C:\Program Files\CMake\bin`


=== Log4cplus

Download the
http://downloads.sourceforge.net/project/log4cplus/log4cplus-stable/1.2.1/log4cplus-1.2.1.tar.xz[source code].
Extract the content to `{BUILD_DIR}`, then proceed with the following commands:

==== On Linux

[source,sh,subs="attributes+"]
$ cd {BUILD_DIR}/log4cplus-1.2.1
$ ./configure CXXFLAGS=-std=c++14 --prefix={DIST_DIR}
$ make -j $(nproc)
$ make install

==== On Windows

[source,sh]
$ cd C:\nutpp\output\log4cplus-1.2.1\msvc10
$ msbuild log4cplus.sln /target:log4cplus /p:Configuration=Release /p:PlatformToolset=v140


=== OpenSSL

==== On Linux

Use the packages offered by the standard distribution.
[source,sh]
$ apt-get install openssl libssl-dev

[NOTE]
More details https://help.ubuntu.com/community/OpenSSL#Practical_OpenSSL_Usage[here].

==== On Windows

Obtain pre-compiled win 32/64 libraries without external dependencies to
the Microsoft Visual Studio Runtime DLLs, except for the system provided
`msvcrt.dll`.

Go to https://indy.fulgan.com/SSL/ and download the latest archive
suitable for your distribution, e.g. `openssl-1.0.2d-x64_86-win64.zip`.
Unpack the archive in `{DIST_DIR}`.


=== Boost

The _Wt_ library depends on the following boost components: filesystem,
program_options, system, thread, atomic, chrono, date_time.

[NOTE]
`atomic`, `chrono` and `date_time` are actually internal dependencies for `thread`.
See `FindBoost.cmake` for details.

[WARNING]
====
CMake reports errors if the Boost version is not supported:
----
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version 106400
----
In the example above, CMake v3.5 doesn't recognize Boost v1.64 and
is necessary to downgrade Boost to an older version.
You may check `FindBoost.cmake` for hints regarding the latest supported:
----
 elseif(NOT Boost_VERSION VERSION_LESS 106000 AND Boost_VERSION VERSION_LESS 106200)
----
That means we must NOT use Boost v1.62 and newer.
====

Download the
http://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2[source code].
Extract the content to `{BUILD_DIR}`, then proceed with the following commands:

==== On Linux

[source,sh,subs="attributes+"]
$ cd {BUILD_DIR}/boost_1_61_0
$ ./bootstrap.sh --without-icu \
    --without-libraries=container,context,coroutine,coroutine2,exception,graph,graph_parallel,iostreams,locale,log,math,mpi,python,random,regex,serialization,signals,test,timer,type_erasure,wave \
    --prefix="{DIST_DIR}"
$ ./b2 -j $(nproc) toolset=gcc cxxflags=-std=c++14 variant=release \
    threading=multi link=shared runtime-link=shared --layout=system install

[TIP]
Starting with Boost v1.62 there is a new component `fiber` that may also
be added to the list of excluded libraries.

==== On Windows

Same as building on Linux, just replace `bootstrap.sh` with `bootstrap.bat`.


=== Wt library

Download the https://github.com/emweb/wt/archive/4.0.2.tar.gz[source code].
Extract the content to `{BUILD_DIR}`, then proceed with the following commands:

[source,sh,subs="attributes+"]
$ cd {BUILD_DIR}/wt-4.0.2
$ cmake \
    -DCMAKE_PREFIX_PATH="{DIST_DIR}" \
    -DCMAKE_INSTALL_PREFIX="{DIST_DIR}" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=14 \
    -DCONNECTOR_HTTP=ON -DENABLE_SSL=ON -DENABLE_LIBWTDBO=ON -DENABLE_SQLITE=ON \
    -DCONNECTOR_FCGI=OFF -DENABLE_HARU=OFF -DENABLE_PANGO=OFF -DENABLE_EXT=OFF \
    -DENABLE_POSTGRES=OFF -DENABLE_FIREBIRD=OFF -DENABLE_MYSQL=OFF \
    -DENABLE_MSSQLSERVER=OFF -DENABLE_QT4=OFF -DENABLE_LIBWTTEST=OFF \
    -DENABLE_OPENGL=OFF -DINSTALL_EXTENSIONLESS_HEADERS=OFF \
    -DENABLE_UNWIND=OFF -DDEBUG=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF
$ make -j $(nproc)
$ make install


=== RapidJSON (not used for the moment)

_RapidJSON_ is a header only library. Obtain a copy of the library from
https://github.com/miloyip/rapidjson/archive/master.zip


=== Doxygen (optional)

==== On Linux

Install `doxygen` and, optionally, `graphviz` packages:

[source,sh]
$ sudo apt-get install doxygen graphviz

[TIP]
Doxygen uses the `dot` tool from `graphviz`, if available, to generate
more advanced diagrams and graphs.

==== On Windows

Download http://www.stack.nl/~dimitri/doxygen/download.html[doxygen sources]
and follow the normal installation flow.


== Build nutpp

The instructions bellow assume the _nutpp_ source code resides in `{NUTPP_DIR}`.

In order to keep the source folder clean, you can create a separate
build folder and execute the `cmake` command there:
[source,sh,subs="attributes+"]
$ mkdir {BUILD_DIR}/nutpp
$ cd {BUILD_DIR}/nutpp

Make sure to replace the `<BUILD_ARGS>` in the commands bellow with the
appropriate configuration on your system:
[source,sh,subs="attributes+"]
-DCMAKE_PREFIX_PATH="{DIST_DIR}" \
-DCMAKE_INSTALL_PREFIX="{DIST_DIR}" \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_ECLIPSE_VERSION=4.7.2 \
-DCMAKE_ECLIPSE_MAKE_ARGUMENTS=-j4 \
-DBUILD_DOCS=OFF

=== Using CLI on Linux

[source,sh,subs="attributes+"]
$ cmake -G "Unix Makefiles" <BUILD_ARGS> {NUTPP_DIR}

=== Using CLI on Windows

[source,sh,subs="attributes+"]
$ cmake -G "Unix Makefiles" <BUILD_ARGS> {NUTPP_DIR}

=== Using Eclipse on Linux

[source,sh,subs="attributes+"]
$ cmake -G "Eclipse CDT4 - Unix Makefiles" <BUILD_ARGS> {NUTPP_DIR}

=== Using Eclipse on Windows

[source,sh,subs="attributes+"]
$ cmake -G "Eclipse CDT4 - NMake Makefiles" <BUILD_ARGS> {NUTPP_DIR}

=== Using Visual Studio

[source,sh,subs="attributes+"]
$ cmake -G "Visual Studio 14 2015" <BUILD_ARGS> {NUTPP_DIR}


== Create nutpp distributable

TODO: stripping enabled in main cmake config
