= nutpp
Cristian Ciocaltea <cristian.ciocaltea@gmail.com>
ifdef::env-github[]
:imagesdir: https://github.com/cristicc/nutpp/blob/master/docs
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:imagesdir: ./docs
endif::[]
:toc:
:toc-placement!:
:sectnums:
:sectanchors:
:sectlinks:

_nutpp_ is an utility web application written in C++ to be used by nutritionists
to create nutrition plans.

toc::[]

IMPORTANT: This is currently a work in progress..

== Purpose

TODO

== Deployment and Configuration

Please read the link:INSTALL.adoc[installation guide] for details about
building and installing the application on the build platform. Additionally,
if provides instructions on how to create a distributable package.

TODO

=== Enable Google OAuth2

To use OAuth service for Google as third-party authenticator, follow the
steps bellow:

* Create a new project for nutpp application on:
    https://console.developers.google.com

* Create `OAuth 2.0 client ID` credential for application type `Web Application`
 - Note the generated `Client ID` and `Client secret`
 - Authorized redirect URIs: http://localhost:8080/google-oauth2callback
